-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS lab2."Room"
(
    id integer,
    name character varying NOT NULL,
    space numeric NOT NULL,
    space_left numeric NOT NULL,
    min_humidity numeric NOT NULL,
    max_humidity numeric NOT NULL,
    min_temp numeric NOT NULL,
    max_temp numeric NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uni_room_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS lab2."Shelf"
(
    shelf_id integer,
    room_id integer NOT NULL,
    max_spaces integer NOT NULL,
    spaces_left integer NOT NULL,
    slot_w numeric NOT NULL,
    slot_h numeric NOT NULL,
    slot_l numeric NOT NULL,
    max_weight numeric NOT NULL,
    weight_left numeric NOT NULL,
    PRIMARY KEY (shelf_id)
);

CREATE TABLE IF NOT EXISTS lab2."Client"
(
    client_id integer,
    name character varying NOT NULL,
    requisites text NOT NULL,
    PRIMARY KEY (client_id),
    CONSTRAINT uni_client_requisites UNIQUE (requisites)
);

CREATE TABLE IF NOT EXISTS lab2."Contract"
(
    contract_id integer,
    expiration_date date NOT NULL,
    signing_date date NOT NULL,
    client_id integer NOT NULL,
    PRIMARY KEY (contract_id)
);

CREATE TABLE IF NOT EXISTS lab2."Product"
(
    product_id integer,
    width numeric NOT NULL,
    height numeric NOT NULL,
    length numeric NOT NULL,
    unpacing_date date NOT NULL,
    contract_id integer NOT NULL,
    max_humid numeric NOT NULL,
    min_humid numeric NOT NULL,
    max_temp numeric NOT NULL,
    min_temp numeric NOT NULL,
    shelf_id integer NOT NULL,
    slot_id integer NOT NULL,
    weight numeric NOT NULL,
    PRIMARY KEY (product_id)
);

ALTER TABLE IF EXISTS lab2."Shelf"
    ADD FOREIGN KEY (room_id)
    REFERENCES lab2."Room" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS lab2."Contract"
    ADD FOREIGN KEY (client_id)
    REFERENCES lab2."Client" (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS lab2."Product"
    ADD FOREIGN KEY (shelf_id)
    REFERENCES lab2."Shelf" (shelf_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS lab2."Product"
    ADD FOREIGN KEY (contract_id)
    REFERENCES lab2."Contract" (contract_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;