# Базовые параметры настройки конфигурации проекта
dbname: lab6p # В классе менять не надо
user: postgres # Замените на свой логин от БД в классе
password: 123 # Замените на свой пароль от БД в классе
host: localhost # Замените на 192.168.0.48 в классе
dbtableprefix: '"C21-703-7".'  # Замените на свой логин от БД
port: 5433